import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Titan Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <iframe className="flex min-h-screen" src='https://my.spline.design/colorbox2copy-f1f6aed885d8775fbc0e5c8f0c4635b3/' width='100%' height='100%' ></iframe>
        <div className="container mx-auto z-20 px-4">
        <NavBar></NavBar>
        </div>
      </div>
    </div>
  );
};

export default Home;
